Create DATABASE IF NOT EXISTS LOGIN;

USE LOGIN;

CREATE TABLE IF NOT EXISTS LOGIN
(
	LOGIN VARCHAR(20) NOT NULL PRIMARY KEY,
    SENHA VARCHAR(20)
);

INSERT INTO LOGIN VALUES('GABRIEL', 'MORAIS');
INSERT INTO LOGIN VALUES ('MARCIO', 'BIGMAC');
INSERT INTO LOGIN VALUES ('VAL', 'TAJMAHAL');
INSERT INTO LOGIN VALUES ('GALLO', 'POKEMON');

